name: update_metadata_dictionary

on:
  # run this action when there's a PR to main branch
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# define jobs/tasks for this action
jobs:
  # changed_files job will query the change status of user-defined files
  changed_files:
    name: changed files test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .github/workflows/update_metadata_dictionary.yml
            requirements.txt
            veoibd.data.model.csv
            **.py
      
      - name: List all changed files from specified list
        # report which of the user-defined files have changed
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'
          cache: 'pip'

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pip install -r requirements.txt

      - name: update term files if any defined files have changed
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          python term_file_manager.py
      
      - name: check if term files changed during the workflow execution
        uses: tj-actions/verify-changed-files@v20
        id: changed-term-files
        with:
          files: |
             _data/**/*.csv
      
      - name: update term pages if term csv files or associated scripts has changed
        if: ${{ steps.changed-term-files.outputs.files_changed == 'true' || contains(steps.changed-files.outputs.modified_files, 'term_page_manager.py') }}
        run: |
          python term_page_manager.py
      
      - name: check if term pages changed during the workflow execution
        uses: tj-actions/verify-changed-files@v20
        id: changed-term-pages
        with:
          files: |
             docs/**/*.md
      
      - name: update template page if any term pages or associated script has changed
        if: steps.changed-term-pages.outputs.files_changed == 'true' || contains(steps.changed-files.outputs.modified_files, 'update_template_page.py')
        run: |
          python update_template_page.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          pull: '--rebase --autostash'
          message: 'Updated template files and pages'
