name: update_metadata_dictionary

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: update term files and pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: update term file if data model csv is changed
        if: contains(steps.changed-files.outputs.modified_files, 'veoibd.data.model.csv')
        run: |
          python term_file_manager.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updated term files in _data/'

      - name: Get changed term files
        id: changed-term-files
        uses: dorny/paths-filter@v2
        with:
          base: HEAD
          filters: |
            addedOrdeleted:
              - added|deleted: "_data/**.csv"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: update term page if the availability of term file changed
        if: steps.changed-term-files.outputs.addedOrdeleted == 'true'
        run: |
          python term_page_manager.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updated term pages in docs/'
