name: update_metadata_dictionary

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: update term files and pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: update term files if data model csv is changed
        if: contains(steps.changed-files.outputs.modified_files, 'veoibd.data.model.csv')
        run: |
          python term_file_manager.py

      - name: check if term files changed during the workflow execution
        uses: tj-actions/verify-changed-files@v16
        id: changed-term-files
        with:
          files: |
             _data/*.csv

      - name: update term pages if the availability of term files changed
        if: steps.changed-term-files.outputs.files_changed == 'true'
        run: |
          python term_page_manager.py
      
      - name: check if term pages changed during the workflow execution
        uses: tj-actions/verify-changed-files@v16
        id: changed-term-pages
        with:
          files: |
             docs/**/*.md

      - name: update template page if the availability of term page changed
        if: steps.changed-term-pages.outputs.files_changed == 'true'
        run: |
          python update_template_page.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          pull: '--rebase --autostash'
          message: 'Updated template files and pages'

